apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app-vote
  template:
    metadata:
      labels:
        app: voting-app-vote
    spec:
      containers:
      - name: voting-app-vote
        image: omprakashsirvibose/votingapp-vote:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          periodSeconds: 10
          initialDelaySeconds: 10
        env:
          - name: REDIS_HOST
            value: redis-service.default
          - name: OPTION_A
            value: Cats
          - name: OPTION_B
            value: Dogs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"


