apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: omprakashsirvibose/votingapp-worker:latest
        env:
          - name: REDIS_HOST
            value: redis-service.default
          - name: DB_HOST
            value: db-service.default
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
