apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  volumeName: db-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
