apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: voting-app-vote
  ports:
    - protocol: 'TCP'
      # This is the port I want to expose to outside world
      port: 5000
      # This port is the application exposed port
      targetPort: 80

  type: LoadBalancer